// Generated by scripts/build-extension.js. Do not edit directly.
//
// The userscript registers its whole control surface through
// GM_registerMenuCommand. In a userscript manager those appear in the
// manager's menu; here the content-script shim records them and this popup
// lists them, invoking each one back in the page.

const statusEl = document.getElementById('status');
const listEl = document.getElementById('commands');

document.getElementById('version').textContent = 'v' + chrome.runtime.getManifest().version;

function show(message) {
  statusEl.textContent = message;
  statusEl.hidden = false;
}

async function activeTabId() {
  const [tab] = await chrome.tabs.query({ active: true, currentWindow: true });
  return tab ? tab.id : null;
}

function send(tabId, message) {
  return new Promise((resolve, reject) => {
    chrome.tabs.sendMessage(tabId, message, (response) => {
      const error = chrome.runtime.lastError;
      if (error) reject(new Error(error.message));
      else resolve(response);
    });
  });
}

async function render() {
  const tabId = await activeTabId();
  if (tabId === null) return show('No active tab.');

  let response;
  try {
    response = await send(tabId, { channel: 'dd-enhanced', type: 'list' });
  } catch (e) {
    return show('Open a DoorDash tab, then reload it once after installing.');
  }
  const commands = (response && response.commands) || [];
  if (!commands.length) return show('No controls registered yet — reload the page.');

  statusEl.hidden = true;
  listEl.textContent = '';
  commands.forEach((label, index) => {
    const button = document.createElement('button');
    button.textContent = label;
    button.addEventListener('click', async () => {
      try {
        await send(tabId, { channel: 'dd-enhanced', type: 'invoke', index });
        window.close();
      } catch (e) {
        show('Could not reach the page. Reload the DoorDash tab.');
      }
    });
    listEl.appendChild(button);
  });
}

render();
